services:
  dermatitisfrontend:
    build: ./frontend
    container_name: dermatitisfrontend
    restart: unless-stopped
    ports:
      - 3000:3000

  dermatitisbackend:
    build: ./backend
    container_name: dermatitisbackend
    restart: unless-stopped
    ports:
      - 8000:8000
