services:
  dermatitis_frontend:
    build: ./frontend
    container_name: dermatitis_frontend
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - dermatitis_network

  dermatitis_backend:
    build: ./backend
    container_name: dermatitis_backend
    restart: unless-stopped
    ports:
      - 8081:8000
    networks:
      - dermatitis_network

  redis:
    image: redis:8.0-M03-bookworm
    container_name: dermatitis_redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - dermatitis_network
    volumes:
      - redis_data:/data

networks:
  dermatitis_network:
    driver: bridge
